### ISSUE TITLE
cordova init not working

### ISSUE THREAD

**Issue by Chalkin** [kartsims/vue-cordova-demo#1]
`cordova init` throws the following error: Error: Cordova does not know init; try `cordova help` for a list of all the available commands.

According to your readme it should work.

**Comment by kartsims** [comment]
Did you get any error/warning during `npm install` ?

If so, could you try running `npm run build` _before_  `cordova init`?

Please state your version of cordova (`cordova -v`)

**Comment by Chalkin** [comment]
No, no errors during npm install. npm run build is working and after that same error with cordova init. cordova -v 6.3.1

**Comment by kartsims** [comment]
Thanks for pointing that out. It seems that cordova's 6.x version doesn't support `cordova init` anymore

I have updated the whole repo so beware, `git pull` might break an error since I started back from scratch.

Please let me know if it now works for you 😃

**Comment by Chalkin** [comment]
thanks for your quick update. I did a new checkout, ran npm install, ran npm run build and did cordova requirements. Once I run cordova run ios I get the following error:

Any Idea?

``````
clang: error: no such file or directory: '/Users/patrick/Sites/vertragsmanager/vue-cordova-demo/platforms/ios/VueCordovaDemo/Plugins/cordova-plugin-camera/CDVCamera.m'
clang: error: no input files

** BUILD FAILED **


The following build commands failed:
    CompileC build/VueCordovaDemo.build/Debug-iphonesimulator/VueCordovaDemo.build/Objects-normal/i386/CDVDevice.o VueCordovaDemo/Plugins/cordova-plugin-device/CDVDevice.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/VueCordovaDemo.build/Debug-iphonesimulator/VueCordovaDemo.build/Objects-normal/i386/UIImage+CropScaleOrientation.o VueCordovaDemo/Plugins/cordova-plugin-camera/UIImage+CropScaleOrientation.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/VueCordovaDemo.build/Debug-iphonesimulator/VueCordovaDemo.build/Objects-normal/i386/CDVJpegHeaderWriter.o VueCordovaDemo/Plugins/cordova-plugin-camera/CDVJpegHeaderWriter.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/VueCordovaDemo.build/Debug-iphonesimulator/VueCordovaDemo.build/Objects-normal/i386/CDVCamera.o VueCordovaDemo/Plugins/cordova-plugin-camera/CDVCamera.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/****/vue-cordova-demo/platforms/ios/cordova/build-debug.xcconfig,-project,VueCordovaDemo.xcodeproj,-target,VueCordovaDemo,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/****/vue-cordova-demo/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/****/vue-cordova-demo/platforms/ios/build/sharedpch```

``````

**Comment by kartsims** [comment]
Hmm weird, there seems to be an issue with the plugins... Please try `cordova plugin add cordova-plugin-camera cordova-plugin-device` and let me know how it goes after that

**Comment by Chalkin** [comment]
perfect, after cordova remove both plugins and then adding them it worked! thanks a lot!
