### ISSUE TITLE
$ npm run ios,  throw Error

### ISSUE THREAD

**Issue by sfyr111** [kartsims/vue-cordova-demo#10]
$ npm run ios 

Error: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

How should I do?

**Comment by kartsims** [comment]
Hi,

You probably need some xcode-related tooling.

Check out [this issue](https://github.com/nodejs/node-gyp/issues/569#issuecomment-255589932) maybe or [this other one](https://github.com/alrra/dotfiles/issues/13)
