### ISSUE TITLE
Font awesome not loading when app run for ios

### ISSUE THREAD

**Issue by tirjok** [kartsims/vue-cordova-demo#11]

**Comment by kartsims** [comment]
Please be more specific and provide code example. There is no reason why font awesome or any css library wouldn't work.

Maybe check for absolute/relative paths as Cordova apps are executed through `file://` on devices

**Comment by tirjok** [comment]
Helo @kartsims 
Font awesome is loaded and showing while i am in development env. But when i run `npm run ios` app open in simulator, that time there is no font awesome icon showing.

How i imported in App.vue

`<style lang="scss">

  $fa-font-path: '../node_modules/font-awesome/fonts/';
  @import 'node_modules/font-awesome/scss/font-awesome';

</style>
`

**Comment by kartsims** [comment]
It lookes weird that in your code there is `../node_modules` on one line, and `node_modules` and the other... I think the path in the `@import` directive should be relative to the component's location.

I hope this solves your problem ! I am closing this issue unrelated to this particular repository

Have a nice day
