### ISSUE TITLE
Vue router 2 with vue-cordova-demo

### ISSUE THREAD

**Issue by brianbier** [kartsims/vue-cordova-demo#12]
Do you know if vue router 2 is working with Cordova? For some reason my demo app is not working using my router. It completely ignores it.

**Comment by kartsims** [comment]
I really don't see why it woudn't... Are you in hash mode navigation ? One thing that is important is that files are served via `file://` in Cordova apps (not `http://`) and there are some limitations to that. One of them is to use (hash mode navigation](https://router.vuejs.org/en/essentials/history-mode.html).

**Comment by brianbier** [comment]
Yes. That makes sense. Its working now. Thanks for that.
