### ISSUE TITLE
Cannot resolve module 'FileUploadOptions' and 'FileTransfer'

### ISSUE THREAD

**Issue by webloper** [kartsims/vue-cordova-demo#14]
I am getting this error and unable to resolve the issue, here is the error I am getting. Please tell how to resolve this I am new for webpack

> ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Teacher/Steps.vue
Module not found: Error: Cannot resolve module 'FileUploadOptions' in E:\Projects\sbs-app\src\components\Teacher
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Teacher/Steps.vue 15:25-53

> ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Teacher/Steps.vue
Module not found: Error: Cannot resolve module 'FileTransfer' in E:\Projects\sbs-app\src\components\Teacher
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Teacher/Steps.vue 19:20-43

**Comment by kartsims** [comment]
Providing the actual source code of the `Teacher` component would help. 

But this is not related to this repository anyway. I am closing this issue, please open a question on StackOverflow and post the link here.

**Comment by webloper** [comment]
@kartsims Hi, here is the link of [stackoverflow](https://stackoverflow.com/questions/44747984/cordova-cannot-resolve-module-fileuploadoptions-and-filetransfer) and here is the gist for [teacher component](https://gist.github.com/webloper/742e5ed66534d9da2ecf95738ca7113c)
