### ISSUE TITLE
Vue 2.0

### ISSUE THREAD

**Issue by vietquocnguyen** [kartsims/vue-cordova-demo#2]
Do you have any plans to support Vue 2.0?

**Comment by kartsims** [comment]
I don't think the VueJS version would cause a probleme with vue-cordova.

But yes I was planning to upgrade vue-cordova-demo to v2, I will do so shorty.

**Comment by kartsims** [comment]
It was actually very easy, code has been updated. Vue 1.x demo has been kept in a dedicated branch for legacy
