### ISSUE TITLE
Browser platform, live reload

### ISSUE THREAD

**Issue by barryvdh** [kartsims/vue-cordova-demo#5]
Is it possible to run the browser platform to serve the cordova.js from there, to 'emulate' Cordova?

You can run the browser platform:

```
cordova platform add browser
cordova prepare browser
cordova serve
```
Will run the browser platform on http://localhost:8000/browser/www/ including cordova.js; http://localhost:8000/browser/www/cordova.js

This will light up your plugins :)

<img width="657" alt="screen shot 2017-01-23 at 22 40 57" src="https://cloud.githubusercontent.com/assets/973269/22223941/18fcb35a-e1bd-11e6-83ae-251719f0af56.png">

But this doesn't have real hot reloading (or at least, cannot get it to work reliable). It needs `npm run build && cordova prepare browser` AND still needs manual refresh :/

It would be awesome use the browser platform + hot reloading together, to quickly test cordova plugins (with emulated behavior).

One idea is to run both `cordova serve` and `npm run dev` parallel together. Hot reload is on 8080, serve on 8000. The plugins don't update that much, so we could do:

```js
// add cordova.js only if serving the app through file://
var cordovaScript
if (window.location.protocol === 'file:') {
  cordovaScript = document.createElement('script')
  cordovaScript.setAttribute('type', 'text/javascript')
  cordovaScript.setAttribute('src', 'cordova.js')
  document.body.appendChild(cordovaScript)
} else if (window.location.host === 'localhost:8080') {
  cordovaScript = document.createElement('script')
  cordovaScript.setAttribute('type', 'text/javascript')
  cordovaScript.setAttribute('src', 'http://localhost:8000/browser/www/cordova.js')
  document.body.appendChild(cordovaScript)
}
```

That would inject cordova.js from the browser platform, while hot reloading the rest.

Thoughts?

**Comment by barryvdh** [comment]
Hmm, so it seems that it does work with `phonegap serve` (on port 3000, so `if (window.location.protocol === 'file:' || window.location.port === '3000') {`)
And run Webpack watch with a simple config based on prod: `webpack -w --config="build/webpack.watch.conf.js"` to build changes directly to the `www` folder.

**Comment by barryvdh** [comment]
Uhh, but that's still 'live reloading' (refreshing on save) and not 'hot reloading' (refreshing but keeping state).

**Comment by kartsims** [comment]
Wow great work, thanks for sharing !

Why would you be using a specific webpack config for `phonegap serve` ? And not the `npm run dev` script that triggers `build/dev-server.js` ?..

If you fork the project so that I can pull and test it somehow, I'd be happy to help

**Comment by barryvdh** [comment]
With phonegap serve, the cordova.js file is also served, with a browser stub. So you can test the `device ready` events etc and simulate some queries. But when just `npm run dev` you only get the non-cordova app events/functions, right?

**Comment by kartsims** [comment]
hmm I am not sure what you mean by "non-cordova" stuff ?

`npm run dev` starts a small environment that loads the JS and assets through webpack, mostly (only?) using a websocket so that the hot reload is triggered. It doesn't mean you can't load the `cordova.js` file, by loading it through JS

Running the dev script and checking your Chrome console might be a better way to understand than reading my fuzzy explanation though.

**Comment by barryvdh** [comment]
But how do you get the cordova.js file? Thats generated with `cordova prepare browser` to include the plugins, right?

Left: phonegap serve
Right: npm run dev
<img width="1264" alt="screen shot 2017-01-24 at 17 05 02" src="https://cloud.githubusercontent.com/assets/973269/22255823/f1673846-e258-11e6-9b92-174e3f5f5ad1.png">

**Comment by kartsims** [comment]
could you please provide a repo that I can clone/pull to work on ? I'll try to look into it during my commute tonight

**Comment by barryvdh** [comment]
No I just used this exact repository. Are you saying you get the device ready event with this package, just with `npm run dev`?
You only add it on file:// 
https://github.com/kartsims/vue-cordova-demo/blob/84400d274a6be6426b40ab1042db5834ed1bac03/src/main.js#L9-L15

So not on http://localhost..
And otherwise, where does the cordova.js come from? Phonegap/cordova serve adds it (platforms/browser/www/cordova.js, cordova_plugins.js etc)

**Comment by barryvdh** [comment]
Alrighty, this is what I mean: https://github.com/kartsims/vue-cordova-demo/pull/6

**Comment by kartsims** [comment]
Merged into master, thanks for your help !
