### ISSUE TITLE
example of iOSRTC support

### ISSUE THREAD

**Issue by jamesyoung** [kartsims/vue-cordova-demo#7]
Would it be possible to update the demo app to support iosrtc?

https://github.com/eface2face/cordova-plugin-iosrtc

**Comment by kartsims** [comment]
There is a long list of plugins that need to be supported but I will surely add this one to it. 

Not sure when it will be released though

**Comment by kartsims** [comment]
Plugins support don't belong to this repo but to [vue-cordova](https://github.com/kartsims/vue-cordova)

If you want to implement it, please send a PR there and a PR to this repo for an implementation example
